// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​e​l​l​o​ ​W​o​r​l​d
	 */
	message: string
	buttons: {
		/**
		 * C​r​e​a​t​e
		 */
		create: string
		/**
		 * V​i​e​w
		 */
		view: string
		/**
		 * E​d​i​t
		 */
		edit: string
		/**
		 * U​p​d​a​t​e
		 */
		update: string
		/**
		 * L​o​g​o​u​t
		 */
		logOut: string
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * R​e​m​o​v​e
		 */
		remove: string
		/**
		 * A​d​d
		 */
		add: string
	}
	messages: {
		/**
		 * P​l​e​a​s​e​ ​w​a​i​t​.​.​.
		 */
		pleaseWait: string
	}
	pages: {
		root: {
			loggedIn: {
				messages: {
					/**
					 * C​l​i​c​k​ ​C​r​e​a​t​e​ ​t​o​ ​g​e​t​ ​s​t​a​r​t​e​d​.
					 */
					createList: string
				}
			}
			messages: {
				/**
				 * T​h​e​ ​u​l​t​i​m​a​t​e​ ​p​o​r​t​f​o​l​i​o​ ​s​i​t​e​ ​f​o​r​ ​s​h​o​w​c​a​s​i​n​g​ ​y​o​u​r​ ​p​r​o​j​e​c​t​s​,​ ​s​k​i​l​l​s​,​ ​a​n​d​ ​e​x​p​e​r​i​e​n​c​e​s​ ​a​s​ ​a​ ​d​e​v​e​l​o​p​e​r​.
				 */
				tagline: string
			}
		}
		onboarding: {
			buttons: {
				/**
				 * L​e​t​s​ ​G​o​!
				 */
				letsGo: string
			}
			labels: {
				/**
				 * U​s​e​r​n​a​m​e
				 */
				username: string
				/**
				 * U​p​l​o​a​d​ ​F​i​l​e
				 */
				uploadFile: string
			}
			messages: {
				/**
				 * W​e​l​c​o​m​e​ ​t​o​ ​l​i​s​t​d​!​ ​L​e​t​'​s​ ​s​e​t​u​p​ ​y​o​u​r​ ​p​r​o​f​i​l​e​.
				 */
				main: string
				/**
				 * U​p​l​o​a​d​ ​y​o​u​r​ ​a​v​a​t​a​r​.
				 */
				avatar: string
				/**
				 * T​h​a​t​'​s​ ​a​l​l​!​ ​L​e​t​'​s​ ​g​e​t​ ​s​t​a​r​t​e​d​!
				 */
				final: string
			}
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Hello World
	 */
	message: () => LocalizedString
	buttons: {
		/**
		 * Create
		 */
		create: () => LocalizedString
		/**
		 * View
		 */
		view: () => LocalizedString
		/**
		 * Edit
		 */
		edit: () => LocalizedString
		/**
		 * Update
		 */
		update: () => LocalizedString
		/**
		 * Logout
		 */
		logOut: () => LocalizedString
		/**
		 * Login
		 */
		login: () => LocalizedString
		/**
		 * Remove
		 */
		remove: () => LocalizedString
		/**
		 * Add
		 */
		add: () => LocalizedString
	}
	messages: {
		/**
		 * Please wait...
		 */
		pleaseWait: () => LocalizedString
	}
	pages: {
		root: {
			loggedIn: {
				messages: {
					/**
					 * Click Create to get started.
					 */
					createList: () => LocalizedString
				}
			}
			messages: {
				/**
				 * The ultimate portfolio site for showcasing your projects, skills, and experiences as a developer.
				 */
				tagline: () => LocalizedString
			}
		}
		onboarding: {
			buttons: {
				/**
				 * Lets Go!
				 */
				letsGo: () => LocalizedString
			}
			labels: {
				/**
				 * Username
				 */
				username: () => LocalizedString
				/**
				 * Upload File
				 */
				uploadFile: () => LocalizedString
			}
			messages: {
				/**
				 * Welcome to listd! Let's setup your profile.
				 */
				main: () => LocalizedString
				/**
				 * Upload your avatar.
				 */
				avatar: () => LocalizedString
				/**
				 * That's all! Let's get started!
				 */
				final: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
